import subprocess
import sys
import time
import os
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

class ReloadHandler(FileSystemEventHandler):
    def __init__(self):
        self.process = None
        self.last_reload = 0
        self.debounce_seconds = 1.0
        self.target_script = "main.py"
    
    def _is_python_file(self, path: str) -> bool:
        """Return True for Python source files we care about."""
        if not path.endswith(".py"):
            return False
        # Ignore cache folders or temp files generated by editors
        parts = os.path.normpath(path).split(os.sep)
        if "__pycache__" in parts:
            return False
        filename = os.path.basename(path)
        if filename.startswith(".") or filename.endswith("~"):
            return False
        return True

    def _debounced(self) -> bool:
        """Throttle how often we restart to avoid duplicate events."""
        current_time = time.time()
        if current_time - self.last_reload < self.debounce_seconds:
            return False
        self.last_reload = current_time
        return True
        
    def on_modified(self, event):
        if event.is_directory or not self._is_python_file(event.src_path):
            return
        if not self._debounced():
            return

        changed_file = os.path.relpath(event.src_path)
        print(f"File changed: {changed_file} - restarting app...")
        self.restart_app()
    
    def start_app(self):
        """Start the app normally"""
        if self.process and self.process.poll() is None:
            # Already running
            return
        self.process = subprocess.Popen([sys.executable, self.target_script])
    
    def restart_app(self):
        """Restart the running app process after a file change."""
        self.stop()
        self.start_app()
    
    def stop(self):
        if self.process:
            self.process.terminate()
            try:
                self.process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.process.kill()
            finally:
                self.process = None

def main():
    print("Starting Flet app with auto-reload...")
    print("Press Ctrl+C to stop")
    
    handler = ReloadHandler()
    handler.start_app()
    
    observer = Observer()
    observer.schedule(handler, '.', recursive=True)
    observer.start()
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nStopping...")
        observer.stop()
        handler.stop()
    
    observer.join()

if __name__ == "__main__":
    main()
