using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Text.Json.Serialization;

namespace Affine.Engine.Model.Auditing.Assessment
{
    /// <summary>
    /// Base class containing common properties for risk assessment references
    /// </summary>
    public abstract class RiskAssessmentReferenceBase
    {
        public string Client { get; set; }
        public DateTime? AssessmentStartDate { get; set; }
        public DateTime? AssessmentEndDate { get; set; }
        public string Assessor { get; set; }
        public string ApprovedBy { get; set; }
    }

    /// <summary>
    /// Input model for creating a new risk assessment reference.
    /// Does NOT include ReferenceId since it's auto-generated by the database.
    /// </summary>
    public class RiskAssessmentReferenceInput : RiskAssessmentReferenceBase
    {
        // No additional properties - ReferenceId is intentionally excluded
    }

    /// <summary>
    /// Output model for reading risk assessment references.
    /// Includes the database-generated ReferenceId.
    /// </summary>
    public class RiskAssessmentReference : RiskAssessmentReferenceBase
    {
        /// <summary>
        /// Database-generated ID of this reference record.
        /// </summary>
        public int ReferenceId { get; set; }
    }
}
